name: Build

on:
  workflow_call:
    inputs:
      checkout_ref:
        required: true
        type: string
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
        # Set work dir to "project" for all 'run' calls. Beware, everything else
        # (actions, 'with' params, etc.) still needs to reference full path.
        working-directory: project

    steps:
      - name: Checkout last PR commit
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: project

      - name: Checkout last tag
        if: github.event_name == 'workflow_dispatch'
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.checkout_ref }}
          path: project

      - name: Retrieve cache
        uses: actions/cache@v3
        env:
          cache-name: cache-modules
        with:
          path: |
            bootloader
            modules
            nrf
            nrfxlib
            test
            tools
            zephyr
            ~/.local/share/east/downloads/
            ~/.local/share/east/nrfutil-toolchain-manager.exe
          # Note above two lines, if we are caching entire ~/.local/share/east
          # folder then cache action fails during download/extract step
          key:
            ${{ runner.os }}-build-${{ env.cache-name }}-${{
            hashFiles('project/west.yml') }}
          restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          cache: "pip"
          cache-dependency-path: project/scripts/requirements.txt

      - name: Install dependencies
        run: make install-dep

      - name: Setup project
        run: make project-setup

      - name: Pre-build
        run: make pre-build

      - name: Build
        run: make build

      - name: Pre-package
        if: github.event_name == 'workflow_dispatch'
        run: make post-build

      - name: Package artefacts
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v3
        with:
          name: artefacts
          path: project/artefacts/*
